# This file contains hyperparameters for all the different experiments we want
# to run. This makes it easier to keep track of all the settings across
# different experiments. Note that experiments are seperated by triple dots
# (---).

path_to_save: ./experiments/resnet50/adam/

parameters:
  num_hidden: 512
  embedding_dim: 512
  batch_size: 64
  num_layers: 2
  lr: 0.001
  epochs: 200
  
  encoder: resnet50
  optimizer: Adam

--- 

path_to_save: ./experiments/resnet50/rmsprop/

parameters:
  num_hidden: 512
  embedding_dim: 512
  batch_size: 64
  num_layers: 2
  lr: 0.001
  epochs: 200
  
  encoder: resnet50
  optimizer: RMSProp

---

# additional experiments here...
