# This file contains hyperparameters for all the different experiments we want
# to run. This makes it easier to keep track of all the settings across
# different experiments. Note that experiments are seperated by triple dots
# (---).

experiment-name: exp1
save_folder: ./experiments/learning_rate_0.1

parameters:
  lr: 0.1
  batch_size: 64
  epochs: 100

--- 

experiment-name: exp2
save_folder: ./experiments/learning_rate_0.01

parameters:
  lr: 0.01
  batch_size: 64
  epochs: 100

---

# additional experiments here...
